function [fitresult, gof] = createFit(n, iterations)
%CREATEFIT(N,ITERATIONS)
%  Create a fit.
%
%  Data for 'Linear regression' fit:
%      X Input : n
%      Y Output: iterations
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Oct-2013 18:48:34


%% Fit: 'Linear regression'.
[xData, yData] = prepareCurveData( n, iterations );

% Set up fittype and options.
ft = fittype( 'poly5' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf];
opts.Upper = [Inf Inf Inf Inf Inf Inf];
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Linear regression' );
h = plot( fitresult, xData, yData );
legend( h, 'iterations vs. n', 'Linear regression', 'Location', 'NorthEast' );
% Label axes
xlabel( 'n' );
ylabel( 'iterations' );
grid on


